### ISSUE TITLE
TypeError: long2ip(): Localhost / Domain

### ISSUE THREAD

**Issue by juanjox20** [Znote/ZnoteAAC#472]
Hello @Znote 

Some players can create account, others no, me i can only create account using localhost in web, with my domain i can't.
All ports has been opened in router, in computer, all done , all is running fine.

It's maybe an application blocking or interfering with this, but i don't know really. ( using discord, whatsapp.... )

The error log in core/apache/log/error is:

[Tue May 04 23:23:47.843884 2021] [php:error] [pid 16072:tid 1848] [client 192.168.1.254:61113] PHP Fatal error:  Uncaught TypeError: long2ip(): Argument #1 ($ip) must be of type int, string given in C:\\Users\\juan\\Desktop\\UniServerZ\\www\\engine\\function\\general.php:234\nStack trace:\n#0 C:\\Users\\juan\\Desktop\\UniServerZ\\www\\engine\\function\\general.php(234): long2ip()\n#1 C:\\Users\\juan\\Desktop\\UniServerZ\\www\\register.php(83): validate_ip()\n#2 {main}\n  thrown in C:\\Users\\juan\\Desktop\\UniServerZ\\www\\engine\\function\\general.php on line 234, referer: http://global-retro.ddns.net/register.php

I already tried change my IPV6 > IPV4 , set true/false in createcharacter.php and register.php in IPV4, but this doesnt change anything i didnt find nothing on ethernet.

**Comment by Znote** [comment]
You can disable IP validation in config.php:
https://github.com/Znote/ZnoteAAC/blob/855c889568e9f07f5413837cf4ee4ad8f8df3e01/config.php#L569

Your lines in general.php doesn't seem to quite match the latest version either, are you using old/custom version of Znote AAC?

Might be related:
https://github.com/Znote/ZnoteAAC/pull/239

**Comment by juanjox20** [comment]
Hello @Znote ,

The znote version is fresh from here i download it yesterday
I found a lot of themes in ethernet about this, but it seems anything about my provider with ipv4/ipv6 error.

At least i would try this and i keep you informed

**Comment by ForgottenOldschool** [comment]
i have a related issue. if i use my masked with a.ml domain for example, players can't login into their accounts via website
